//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelAnalyzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModelAnalyzer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure clause is invalid..
        /// </summary>
        internal static string BadEnsureAnalyzerDescription {
            get {
                return ResourceManager.GetString("BadEnsureAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure clause &apos;{0}&apos; is invalid.
        /// </summary>
        internal static string BadEnsureAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("BadEnsureAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure clause is invalid.
        /// </summary>
        internal static string BadEnsureAnalyzerTitle {
            get {
                return ResourceManager.GetString("BadEnsureAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression is invalid..
        /// </summary>
        internal static string BadExpressionAnalyzerDescription {
            get {
                return ResourceManager.GetString("BadExpressionAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression is invalid.
        /// </summary>
        internal static string BadExpressionAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("BadExpressionAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression is invalid.
        /// </summary>
        internal static string BadExpressionAnalyzerTitle {
            get {
                return ResourceManager.GetString("BadExpressionAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field is not supported..
        /// </summary>
        internal static string BadFieldAnalyzerDescription {
            get {
                return ResourceManager.GetString("BadFieldAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; is not supported.
        /// </summary>
        internal static string BadFieldAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("BadFieldAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field is not supported.
        /// </summary>
        internal static string BadFieldAnalyzerTitle {
            get {
                return ResourceManager.GetString("BadFieldAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class invariant is invalid..
        /// </summary>
        internal static string BadInvariantAnalyzerDescription {
            get {
                return ResourceManager.GetString("BadInvariantAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class invariant &apos;{0}&apos; is invalid.
        /// </summary>
        internal static string BadInvariantAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("BadInvariantAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class invariant is invalid.
        /// </summary>
        internal static string BadInvariantAnalyzerTitle {
            get {
                return ResourceManager.GetString("BadInvariantAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local variable is not supported..
        /// </summary>
        internal static string BadLocalAnalyzerDescription {
            get {
                return ResourceManager.GetString("BadLocalAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local variable &apos;{0}&apos; is not supported.
        /// </summary>
        internal static string BadLocalAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("BadLocalAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local variable is not supported.
        /// </summary>
        internal static string BadLocalAnalyzerTitle {
            get {
                return ResourceManager.GetString("BadLocalAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method is not supported..
        /// </summary>
        internal static string BadMethodAnalyzerDescription {
            get {
                return ResourceManager.GetString("BadMethodAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; is not supported.
        /// </summary>
        internal static string BadMethodAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("BadMethodAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method is not supported.
        /// </summary>
        internal static string BadMethodAnalyzerTitle {
            get {
                return ResourceManager.GetString("BadMethodAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter is not supported..
        /// </summary>
        internal static string BadParameterAnalyzerDescription {
            get {
                return ResourceManager.GetString("BadParameterAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; is not supported.
        /// </summary>
        internal static string BadParameterAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("BadParameterAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter is not supported.
        /// </summary>
        internal static string BadParameterAnalyzerTitle {
            get {
                return ResourceManager.GetString("BadParameterAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require clause is invalid..
        /// </summary>
        internal static string BadRequireAnalyzerDescription {
            get {
                return ResourceManager.GetString("BadRequireAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require clause &apos;{0}&apos; is invalid.
        /// </summary>
        internal static string BadRequireAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("BadRequireAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require clause is invalid.
        /// </summary>
        internal static string BadRequireAnalyzerTitle {
            get {
                return ResourceManager.GetString("BadRequireAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement is invalid..
        /// </summary>
        internal static string BadStatementAnalyzerDescription {
            get {
                return ResourceManager.GetString("BadStatementAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement is invalid.
        /// </summary>
        internal static string BadStatementAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("BadStatementAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement is invalid.
        /// </summary>
        internal static string BadStatementAnalyzerTitle {
            get {
                return ResourceManager.GetString("BadStatementAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in class model..
        /// </summary>
        internal static string ClassModelAnalyzerDescription {
            get {
                return ResourceManager.GetString("ClassModelAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in class &apos;{0}&apos; model.
        /// </summary>
        internal static string ClassModelAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("ClassModelAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in class model.
        /// </summary>
        internal static string ClassModelAnalyzerTitle {
            get {
                return ResourceManager.GetString("ClassModelAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method ensure clause is violated..
        /// </summary>
        internal static string EnsureViolationAnalyzerDescription {
            get {
                return ResourceManager.GetString("EnsureViolationAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; ensure clause &apos;{1}&apos; is violated.
        /// </summary>
        internal static string EnsureViolationAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("EnsureViolationAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method ensure clause is violated.
        /// </summary>
        internal static string EnsureViolationAnalyzerTitle {
            get {
                return ResourceManager.GetString("EnsureViolationAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class invariant is violated..
        /// </summary>
        internal static string InvariantViolationAnalyzerDescription {
            get {
                return ResourceManager.GetString("InvariantViolationAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class &apos;{0}&apos; invariant &apos;{1}&apos; is violated.
        /// </summary>
        internal static string InvariantViolationAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("InvariantViolationAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class invariant is violated.
        /// </summary>
        internal static string InvariantViolationAnalyzerTitle {
            get {
                return ResourceManager.GetString("InvariantViolationAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method require clause is violated..
        /// </summary>
        internal static string RequireViolationAnalyzerDescription {
            get {
                return ResourceManager.GetString("RequireViolationAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; require clause &apos;{1}&apos; is violated.
        /// </summary>
        internal static string RequireViolationAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("RequireViolationAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method require clause is violated.
        /// </summary>
        internal static string RequireViolationAnalyzerTitle {
            get {
                return ResourceManager.GetString("RequireViolationAnalyzerTitle", resourceCulture);
            }
        }
    }
}
