//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoAnalyzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DemoAnalyzer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad expression..
        /// </summary>
        internal static string BadExpressionAnalyzerDescription {
            get {
                return ResourceManager.GetString("BadExpressionAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad expression.
        /// </summary>
        internal static string BadExpressionAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("BadExpressionAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad expression.
        /// </summary>
        internal static string BadExpressionAnalyzerTitle {
            get {
                return ResourceManager.GetString("BadExpressionAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad invariant..
        /// </summary>
        internal static string BadInvariantAnalyzerDescription {
            get {
                return ResourceManager.GetString("BadInvariantAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invariant &apos;{0}&apos; is invalid.
        /// </summary>
        internal static string BadInvariantAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("BadInvariantAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class invariant is invalid.
        /// </summary>
        internal static string BadInvariantAnalyzerTitle {
            get {
                return ResourceManager.GetString("BadInvariantAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad parameter..
        /// </summary>
        internal static string BadParameterAnalyzerDescription {
            get {
                return ResourceManager.GetString("BadParameterAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; is invalid.
        /// </summary>
        internal static string BadParameterAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("BadParameterAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter is invalid.
        /// </summary>
        internal static string BadParameterAnalyzerTitle {
            get {
                return ResourceManager.GetString("BadParameterAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad statement..
        /// </summary>
        internal static string BadStatementAnalyzerDescription {
            get {
                return ResourceManager.GetString("BadStatementAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement is invalid.
        /// </summary>
        internal static string BadStatementAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("BadStatementAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement is invalid.
        /// </summary>
        internal static string BadStatementAnalyzerTitle {
            get {
                return ResourceManager.GetString("BadStatementAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class should support a model..
        /// </summary>
        internal static string ClassModelAnalyzerDescription {
            get {
                return ResourceManager.GetString("ClassModelAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class &apos;{0}&apos; should support a model.
        /// </summary>
        internal static string ClassModelAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("ClassModelAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class can be modeled.
        /// </summary>
        internal static string ClassModelAnalyzerTitle {
            get {
                return ResourceManager.GetString("ClassModelAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class invariant is violated..
        /// </summary>
        internal static string InvariantViolationAnalyzerDescription {
            get {
                return ResourceManager.GetString("InvariantViolationAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class &apos;{0}&apos; invariant is violated.
        /// </summary>
        internal static string InvariantViolationAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("InvariantViolationAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class invariant is violated.
        /// </summary>
        internal static string InvariantViolationAnalyzerTitle {
            get {
                return ResourceManager.GetString("InvariantViolationAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables that are not modified should be made constants..
        /// </summary>
        internal static string MakeConstAnalyzerDescription {
            get {
                return ResourceManager.GetString("MakeConstAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable &apos;{0}&apos; can be made constant.
        /// </summary>
        internal static string MakeConstAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("MakeConstAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable can be made constant.
        /// </summary>
        internal static string MakeConstAnalyzerTitle {
            get {
                return ResourceManager.GetString("MakeConstAnalyzerTitle", resourceCulture);
            }
        }
    }
}
