[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("AnalysisLogger")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("ModelAnalyzer.Core")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("ModelAnalyzer.Core.Test")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("ModelAnalyzer.Data")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Verifier")]
